Implement buttons states
code4romania/mon-vot-android-kotlin pull request #70
Opened 2019-10-10 15:49 UTC by pr0t3us

1. Added background selectors for the `Button` and `Button.Black` style.
2. Added `ViewsValidationButton` which should validate the fields based on the set validators (via `OnChangeValidator` interface). 
3. Created several validators to handle different view types: `RadioGroupsValidator`, `SpinnersValidator` and `TextViewsValidator`.
4. Used `RadioGroupsValidator` and `TextViewsValidator` to handle views in `BranchDetailsFragment`, `SpinnersValidator` and `TextViewsValidator` in `BranchSelectionFragment` and `TextViewsValidator` in `NoteFragment`

Fixes #47

2019-10-11 08:11 UTC, AlexandraDaraban commented on app/src/main/java/ro/code4/monitorizarevot/ui/login/LoginActivity.kt
> +import ro.code4.monitorizarevot.widget.validation.TextViewsValidator
Remove unused import

2019-10-11 08:41 UTC, AlexandraDaraban commented on app/src/main/res/drawable/bg_button_dark.xml
> -</shape>
Delete resource if not used

2019-10-11 08:48 UTC, AlexandraDaraban commented on app/src/main/java/ro/code4/monitorizarevot/ui/branch/details/BranchDetailsFragment.kt
> +        val textViewsValidator = TextViewsValidator(arrivalTime, departureTime)
Departure time is optional and should be removed from here

2019-10-11 09:16 UTC, AlexandraDaraban requested changes
Hey, @pr0t3us. Thank you for your contribution. The PR looks good, however there are some issues that I would like you to address before merging the PR. Also, I cloned your repo locally and I noticed the text of the buttons doesn't change when the button is disabled. Could you look more into this, please? Thanks 😄

2019-10-11 11:58 UTC, pr0t3us commented
Hi @AlexandraDaraban thank you for your fair review. I've addressed your comments. Looks like I've imported the wrong alpha channel value for the disabled button color, also I suggest using a more pronounced color for the normal state.

2019-10-29 16:18 UTC, AlexandraDaraban commented
Closed in #115

2019-10-29 16:18 UTC, closed without merging