Create loader for login and get counties
code4romania/mon-vot-android-kotlin pull request #77
Opened 2019-10-13 18:48 UTC by henrikhorbovyi

In this PR I've created a `Result` sealed class to handle data from requests. Also I've created a `Dialog Fragment` to be shown when something is being loaded in background.

closes #44

2019-10-15 10:38 UTC, AlexandraDaraban commented on app/src/main/java/ro/code4/monitorizarevot/ui/login/LoginActivity.kt
> +            )
The only difference between these is the next activity that should be started if the user logged in successfully. You could implement a method that has the activity as a parameter.

2019-10-15 10:41 UTC, AlexandraDaraban commented on app/src/main/java/ro/code4/monitorizarevot/widget/ProgressDialogFragment.kt
> +        const val tag = "ProgressDialogFragment"
You could use `ProgressDialogFragment::class.java.simpleName` and the variable name should be all uppercase.

2019-10-15 10:43 UTC, AlexandraDaraban commented on app/src/main/res/layout/fragment_progress_dialog.xml
> +        app:layout_constraintTop_toTopOf="@+id/progressBar" />
Please apply one of the styles for the `TextView` and use dimensions from the `dimens.xml` for setting margins/paddings

2019-10-15 10:43 UTC, AlexandraDaraban commented on app/src/main/res/layout/fragment_progress_dialog.xml
> +        android:layout_margin="24dp"
Please use dimensions from the `dimens.xml` for setting margins/paddings.

2019-10-15 10:57 UTC, AlexandraDaraban commented on app/src/main/java/ro/code4/monitorizarevot/ui/login/LoginActivity.kt
> +    private val progressDialog: ProgressDialogFragment by lazy { ProgressDialogFragment() }
The `dialog` should be dismissed if the activity is dismissed/closed (e.g: the user dismisses the app while a dialog is shown and a `java.lang.IllegalArgumentException: View not attached to window manager` exception is thrown)

2019-10-15 10:58 UTC, AlexandraDaraban requested changes
Hi @henrikhorbovyi, the PR looks good but there are some issues that I would like you to address. Also, there are some conflicts that also need to be resolved. Thanks!

2019-10-19 15:37 UTC, henrikhorbovyi commented
I'm finishing your change requests, but the worse thing is that, there are conflicts and I should understand how to fix it to don't make a messy :smile:

2019-10-19 17:05 UTC, henrikhorbovyi commented
@AlexandraDaraban I've fixed what you proposed. In this commit  ac61810570f334d58446563f48d650cb35af816d you can check the last changes, cause I had to fix some conflicts.

2019-10-21 13:31 UTC, AlexandraDaraban approved these changes

2019-10-21 13:32 UTC, merged