Fixed toast message display in fragment
code4romania/mon-vot-android-kotlin pull request #80
Opened 2019-10-19 13:38 UTC by sergiuciuperca

Closes #76 

Fixes also a bug when user closes the application before completing section configuration (when the app is opened again it is redirected to Forms that expects a section to be set)

2019-10-21 12:55 UTC, AlexandraDaraban commented on app/src/main/java/ro/code4/monitorizarevot/ui/splashscreen/SplashScreenActivity.kt
> +                LoginActivity::class.java
You could use a `when` expression with multiple conditions instead of `if else`

2019-10-21 12:56 UTC, AlexandraDaraban requested changes
Hey, @sergiuciuperca! The PR looks good but there is a issue that I would like you to look into. Thanks 😄

2019-10-21 14:47 UTC, sergiuciuperca commented
Hi, @AlexandraDaraban, Pushed a commit to fix it :)

2019-10-21 14:57 UTC, AlexandraDaraban commented
@sergiuciuperca , could you please solve the conflicts before merging?

2019-10-21 15:58 UTC, sergiuciuperca commented
@AlexandraDaraban Merged.

Also removed BrachActivity from  Back Stack when navigating to MainActivity.

2019-10-22 08:21 UTC, AlexandraDaraban approved these changes
Looks good!

2019-10-22 08:32 UTC, merged